### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by Geczy** [aseylys/KStock#1]
Is this project still active?

**Comment by aseylys** [comment]
It is, and I'm so sorry nothing has been uploaded yet. I was sent off to training the week I was going to deploy this. I plan on uploading everything in the next 2 weeks now that training is finishing up.

 I also made a server/console version so this can be run in the cloud unlike the GUI so I'll be uploading that too.

Again I'm sorry for the delay.

**Comment by Geczy** [comment]
Congrats on finishing up the training!

Is there a beta / alpha you can upload for now so I can start testing?

**Comment by aseylys** [comment]
I've got an alpha so I'll upload that this weekend

**Comment by Geczy** [comment]
Ready? :)
