### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by Geczy** [aseylys/KStock#2]
Is this because the market is closed today, Sunday? I clicked start and expected to see some activity occur, like checking tickers

![image](https://user-images.githubusercontent.com/1036968/37259873-90e3d756-2562-11e8-8337-da65bd6ad4e1.png)

**Comment by Geczy** [comment]
I added my details to core.cfg this time, and restarted the app

When I click start, it auto pauses a second or two later

![image](https://user-images.githubusercontent.com/1036968/37259904-029a4efc-2563-11e8-946e-c81f0239b04a.png)

**Comment by aseylys** [comment]
Fixed and Uploaded.

**Comment by Geczy** [comment]
It's no longer auto pausing, but also nothing is happening. Should it tell me the market is closed and it can't make purchases? The backend is also empty, no queues are loading

TESTING is enabled 

![image](https://user-images.githubusercontent.com/1036968/37260403-0f4013d4-2569-11e8-8319-61d7d3d06eb9.png)

**Comment by Geczy** [comment]
Testing = TRUE is enabled and it auto pauses , so that's good
