### ISSUE TITLE
Queue and Fetch Lengths Do Not Match

### ISSUE THREAD

**Issue by Geczy** [aseylys/KStock#5]
Whenever I add a new tick to queue I get this error

 _ ~~~~ Queue and Fetch Lengths Do Not Match ~~~~

**Comment by aseylys** [comment]
It's a builtin exception.  

It's caused by the program pruchasing a tick and simultaneously monitoring the the Queue. Once the cycle has finished and the new one starts again (~3 seconds later), the message will be gone.
