### ISSUE TITLE
Everything just staying queued

### ISSUE THREAD

**Issue by Geczy** [aseylys/KStock#6]
I'm using TEST, can you see why nothing is happening? There is one transaction because I made that one manually

![image](https://user-images.githubusercontent.com/1036968/39537313-300a5c2a-4e07-11e8-97eb-bbe09f5cc5cd.png)

![image](https://user-images.githubusercontent.com/1036968/39537323-36599a00-4e07-11e8-9cae-4ead7dc882d2.png)

**Comment by aseylys** [comment]
There isn't anything wrong. KStock looks for the most oppurtune time by analyzing all of the day's data. It puts the prices through a peak detection algorithm, looking for an appropriate valley to purchase. 

Especially for higher priced tickers, trading isn't high frequency, as it shouldn't be. Below $1 you can get into HFT, but above that, it's dependent on when the math says it's good to go.

**Comment by Geczy** [comment]
If I close the program and re-open it, do I lose on the analysis KStock has already done for the day? Does it lose track of where the algorithm is?

**Comment by aseylys** [comment]
Nope. It picks it right back up. 

So sometimes, after restarting, it will immediately buy the ticker because the current price fulfills the zig-zag purchase criteria based on the previous prices throughout the day.
