### ISSUE TITLE
NASDAQ failed

### ISSUE THREAD

**Issue by Geczy** [aseylys/KStock#7]
It always stays failed this morning after starting it at 9:30 

![image](https://user-images.githubusercontent.com/1036968/37286413-3ff9df90-25d8-11e8-9a1f-64d9e7b70c7c.png)

**Comment by Geczy** [comment]
http://www.nasdaq.com/symbol/nvda/real-time
```
Access Denied
You don't have permission to access "http://www.nasdaq.com/symbol/nvda/real-time" on this server.
Reference #18.2e393717.1520861617.20be9d11
```

**Comment by Geczy** [comment]
Looks like I'm unblocked now. May be a rate limit

**Comment by Geczy** [comment]
Blocked again any time I run your python script

**Comment by aseylys** [comment]
It works for me. I've run this with 20+ tickers all fetching at the same time. I'll push an update to include headers just to cover the bases but this problem seems to be more on your side than it does with code.
