### ISSUE TITLE
Cannot get into UI, bizarre timeouts

### ISSUE THREAD

**Issue by klepsydra** [aseylys/KStock#8]
```
Running virtualenv with interpreter /usr/bin/python3.6

root _ INFO _ CLDR Forced Purchase at 
root _ INFO _ T Forced Purchase at 
Traceback (most recent call last):
  File "./KStock.py", line 1024, in <module>
    ex = MainWindow()
  File "./KStock.py", line 100, in __init__
    self.update()
  File "./KStock.py", line 836, in update
    '%.2f' % (float(self.portfolio['extended_hours_equity']))) 
TypeError: float() argument must be a string or a number, not 'NoneType'
```

However, in KStock.py, if I change 

`'%.2f' % (float(self.portfolio['extended_hours_equity']))) `
to
`'%.2f' % (float(self.portfolio['equity']))) `

then after about the same 2min, it still ends abruptly with 
`  root _ INFO _ Market Fetch Timeout`

No GUI every shows.

Around line 53 I tried changing from
`   self.tz = pytz.timezone('US/Eastern')`
to my current timezone, and back,
`   self.tz = pytz.timezone('Europe/Warsaw')`
but it makes no difference.

**Comment by aseylys** [comment]
So this version is super depreciated. Robinhood has updated their API and this version is riddled with bugs. I'm sorry I haven't gotten around to putting the "depreciated" tag on it. 

Currently, I'm working on new version that is cleaner, and handles the new API asynchronously, also it handles more than just Robinhood so the user can choose their broker.

Here's a pic of a demo of it for good measure
![test](https://user-images.githubusercontent.com/3879803/43040741-6a177a30-8d11-11e8-9e73-aeb3f1e3d884.png)

I'm really sorry you experienced problems with the old version, but please be patient, I'm working on uploading the newest version.

**Comment by klepsydra** [comment]
Fantastic work!  With both old and your new upcoming.
Asynchronous sounds great.  I'd be happy to test what you already have
before release.  Besides Robinhood, if yours doesn't yet support TD
Ameritrade, I can provide the API or even attempt to code in the support
myself, depending how cleanly that abstraction is done :)

**Comment by klepsydra** [comment]
Hey @aseylys , have you abandoned this project for now?  What about the version from your demo screenshot?  Where could you use help?

**Comment by aseylys** [comment]
Hey @klepsydra, no it's not abandoned. Life kinda just gets in the way. Honestly it's done but I'm having trouble with performance optimizations. 

With an increasing amount of tickers the program looks at the CPU starts to get overwhelmed and the GUI starts freezing. I've been experimenting with different combos of asynchronous and multiprocessing but can't seem to find a good one that works. Unfortunately I'm still learning about multiprocessing so it's all trial and error. 

I'm going to try an upload what code I have this weekend (beware, it's not at all commented) so maybe you could take a look.
